[package]
name = "find-repos"
version = "0.1.1"
authors = ["Kyle Deal <kdeal@kyledeal.com>"]

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
regex = "1.10.5"

[build-dependencies]
clap = "4.5.7"
