[package]
name = "find-repos"
version = "0.1.1"
authors = ["Kyle Deal <kdeal@kyledeal.com>"]

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
regex = "1.11.1"

[build-dependencies]
clap = "4.5.21"
